// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (uuid, user_id, expires_at)
VALUES (?, ?, ?)
RETURNING uuid, user_id, expires_at
`

type CreateSessionParams struct {
	Uuid      string `json:"uuid"`
	UserID    int64  `json:"user_id"`
	ExpiresAt int64  `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.Uuid, arg.UserID, arg.ExpiresAt)
	var i Session
	err := row.Scan(&i.Uuid, &i.UserID, &i.ExpiresAt)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE uuid = ?
`

func (q *Queries) DeleteSession(ctx context.Context, uuid string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, uuid)
	return err
}

const deleteSessionsByUserID = `-- name: DeleteSessionsByUserID :exec
DELETE FROM sessions
WHERE user_id = ?
`

func (q *Queries) DeleteSessionsByUserID(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsByUserID, userID)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT uuid, user_id, expires_at
FROM sessions
WHERE uuid = ?
`

func (q *Queries) GetSessionByID(ctx context.Context, uuid string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, uuid)
	var i Session
	err := row.Scan(&i.Uuid, &i.UserID, &i.ExpiresAt)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT uuid, user_id, expires_at
FROM sessions
ORDER BY expires_at
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(&i.Uuid, &i.UserID, &i.ExpiresAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
