name: Sprint1 Infra Checks

on:
  pull_request:
    paths:
      - 'labra-infra/**'
      - '.github/workflows/sprint1-infra-check.yml'
  push:
    branches: [main]
    paths:
      - 'labra-infra/**'
      - '.github/workflows/sprint1-infra-check.yml'

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: labra-infra/env/dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.8

      - name: Terraform Fmt
        run: terraform fmt -check -recursive ../..

      - name: Terraform Init (no backend)
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: labra-infra
